server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/ms-user
spring.datasource.username=postgres
spring.datasource.password=Vil3085

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# RabbitMQ CloudAMQP Configuration
spring.rabbitmq.host=seal.lmq.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.username=lbaonxnw
spring.rabbitmq.password=b_EUjIMz8-8OM3R9Wes465arYdzmN70S
spring.rabbitmq.virtual-host=lbaonxnw
spring.rabbitmq.ssl.enabled=true
spring.rabbitmq.ssl.algorithm=TLSv1.2
spring.rabbitmq.connection-timeout=30000
spring.rabbitmq.requested-heartbeat=60

# Fallback para erro de conexão
spring.rabbitmq.template.retry.enabled=true
spring.rabbitmq.template.retry.initial-interval=1000
spring.rabbitmq.template.retry.max-attempts=3

broker.queue.email.name=default.email

# Logs para debug
logging.level.org.springframework.amqp=DEBUG
logging.level.com.rabbitmq=DEBUG